[package]
name = "mysql-slowlog-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
iso8601 = "0.5.1"
sqlparser = {version = "0.30.0", features = ["visitor"]}
thiserror = "1.0.38"

[[example]]
name = "iterator"
path = "examples/iterator.rs"
