[package]
name = "mysql-slowlog-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.4"
futures = "0.3.26"
nom = "7.1.1"
iso8601 = "0.5.1"
sqlparser = {version = "0.30.0", features = ["visitor"]}
thiserror = "1.0.38"
tokio = {version = "1.25.0", features = ["fs", "io-std", "io-util", "rt", "rt-multi-thread", "macros"]}

[[example]]
name = "iterator"
path = "examples/iterator.rs"
