[package]
name = "mysql-slowlog-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
env_logger = "0.11.5"
futures = "0.3.26"
winnow = {  version = "0.6.20", features = ["default"] }
winnow_iso8601 = {  version = "0.1.0" , path = "../winnow-iso8601" }
sqlparser = {version = "0.51.0", features = ["visitor"]}
thiserror = "1.0.38"
log = "0.4.17"
time = {version = "0.3.36", features=["parsing"]}
tokio = {version = "1.25.0", features = ["bytes", "fs", "io-std", "io-util", "rt", "rt-multi-thread", "macros"]}
tokio-util = {version = "0.7.1", features = ["codec"]}


[[example]]
name = "iterator"
path = "examples/iterator.rs"
